// Detalls de cada estàndard: cross-references i accions recomanades
// Importa els tipus de standards-data.ts

import type { StandarDetail } from "./standards-data";

export const STANDARDS_DETAIL: Record<string, StandarDetail> = {
  // ============================================================
  // 1. CSRD / ESRS
  // ============================================================
  "csrd-esrs": {
    slug: "csrd-esrs",
    name: "CSRD / ESRS",
    type: "reg",
    access: "free",
    count: 6,
    logo: "/logos-estandards/csrd-esrs.png",
    issuerCa: "Comissió Europea · EFRAG",
    issuerEs: "Comisión Europea · EFRAG",
    descCa: "Directiva (UE) 2022/2464 de reporting de sostenibilitat. Substitueix el NFRD i obliga ~50.000 empreses europees (11.500 espanyoles) a publicar informació verificable sobre impactes, riscos i oportunitats ESG seguint els European Sustainability Reporting Standards (ESRS). Doble materialitat, format digital (XHTML) i verificació per tercers. Aplicació progressiva: grans cotitzades (FY2024), grans no cotitzades (FY2025), pimes cotitzades (FY2026) i pimes (FY2027). Base de l'ecosistema regulador ESG europeu.",
    descEs: "Directiva (UE) 2022/2464 de reporting de sostenibilidad. Sustituye al NFRD y obliga a ~50.000 empresas europeas (11.500 españolas) a publicar información verificable sobre impactos, riesgos y oportunidades ESG siguiendo los European Sustainability Reporting Standards (ESRS). Doble materialidad, formato digital (XHTML) y verificación por terceros. Aplicación progresiva: grandes cotizadas (FY2024), grandes no cotizadas (FY2025), pymes cotizadas (FY2026) y pymes (FY2027). Base del ecosistema regulador ESG europeo.",
    xrefRows: [
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD (Omnibus II)", date: "6 may 2026",
        criterionCa: "Reducció de datapoints ESRS de ~1.144 a ~600. Materialitat redissenyada per simplificar avaluació. Aplicació a FY2026.",
        criterionEs: "Reducción de datapoints ESRS de ~1.144 a ~600. Materialidad rediseñada para simplificar evaluación. Aplicación a FY2026.",
        impact: "high" },
      { reportTitle: "EFRAG Sustainability Reporting Work Programme 2026", date: "12 feb 2026",
        criterionCa: "Nous Sector Standards en desenvolupament: agricultura, mineria, transport. Convergència amb GRI per reduir duplicació.",
        criterionEs: "Nuevos Sector Standards en desarrollo: agricultura, minería, transporte. Convergencia con GRI para reducir duplicación.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "ESRS S1 (treballadors en la cadena de valor) i S2 (consumidors) es mantenen però s'alineen amb CSDDD due diligence.",
        criterionEs: "ESRS S1 (trabajadores en la cadena de valor) y S2 (consumidores) se mantienen pero se alinean con CSDDD due diligence.",
        impact: "med" },
      { reportTitle: "Verificació limitada ESRS: guia pràctica IAASB", date: "22 abr 2026",
        criterionCa: "Estàndard ISSA 5000 per a verificació limitada de reporting de sostenibilitat. Aplicació obligatòria des de FY2024.",
        criterionEs: "Estándar ISSA 5000 para verificación limitada de reporting de sostenibilidad. Aplicación obligatoria desde FY2024.",
        impact: "high" },
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "Empreses ESRS han de reportar alineació Taxonomia UE en 3 KPIs: turnover, capex, opex. Canvis en criteris tècnics.",
        criterionEs: "Empresas ESRS deben reportar alineación Taxonomía UE en 3 KPIs: turnover, capex, opex. Cambios en criterios técnicos.",
        impact: "med" },
      { reportTitle: "Digital Tagging ESRS: especificacions ESEF", date: "10 feb 2026",
        criterionCa: "Marcador digital obligatori en XHTML. Categorías: Block-tag, Memo-tag. Migració progressiva cap a inline XBRL.",
        criterionEs: "Marcador digital obligatorio en XHTML. Categorías: Block-tag, Memo-tag. Migración progresiva hacia inline XBRL.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Realitzar avaluació de doble materialitat abans del primer cicle de reporting per identificar datapoints aplicables",
        textEs: "Realizar evaluación de doble materialidad antes del primer ciclo de reporting para identificar datapoints aplicables",
        sourceCa: "Font: ESRS 1, Requirements 23-32", sourceEs: "Fuente: ESRS 1, Requirements 23-32" },
      { num: "2", textCa: "Seleccionar verifier (assurance provider) amb acreditació IAASB ISSA 5000 abans del tancament FY2026",
        textEs: "Seleccionar verifier (assurance provider) con acreditación IAASB ISSA 5000 antes del cierre FY2026",
        sourceCa: "Font: Verificació limitada ESRS", sourceEs: "Fuente: Verificación limitada ESRS" },
      { num: "3", textCa: "Implementar sistema de digital tagging ESEF compatible amb plataforma inline XBRL d'EFRAG",
        textEs: "Implementar sistema de digital tagging ESEF compatible con plataforma inline XBRL de EFRAG",
        sourceCa: "Font: Digital Tagging ESRS", sourceEs: "Fuente: Digital Tagging ESRS" },
      { num: "4", textCa: "Aprofitar reducció de datapoints Omnibus II per redefinir el roadmap de implementació amb menys recursos",
        textEs: "Aprovechar reducción de datapoints Omnibus II para redefinir el roadmap de implementación con menos recursos",
        sourceCa: "Font: Revisió ESRS Omnibus II", sourceEs: "Fuente: Revisión ESRS Omnibus II" },
    ],
  },

  // ============================================================
  // 2. GRI
  // ============================================================
  "gri": {
    slug: "gri",
    name: "GRI",
    type: "fw",
    access: "free",
    count: 5,
    logo: "/logos-estandards/gri.png",
    issuerCa: "Global Reporting Initiative · Amsterdam",
    issuerEs: "Global Reporting Initiative · Ámsterdam",
    descCa: "Global Reporting Initiative. Estàndard de reporting de sostenibilitat més usat al món: el 78% de les grans empreses europees i el 70%+ de l'IBEX 35 hi reporten. Estructura modular: Universal Standards (GRI 1-3), Topic Standards (GRI 200 econòmic, 300 ambiental, 400 social) i Sector Standards (cada vegada més sectors: carbó, agricultura, bancari, oli i gas, mineria...). Format de 'material topics' amb participació de stakeholders. Actualització 2021 amb enfocament en impactes reals i drets humans. Convergència activa amb ESRS via mapping EFRAG-GRI.",
    descEs: "Global Reporting Initiative. Estándar de reporting de sostenibilidad más usado del mundo: el 78% de las grandes empresas europeas y el 70%+ del IBEX 35 reportan con él. Estructura modular: Universal Standards (GRI 1-3), Topic Standards (GRI 200 económico, 300 ambiental, 400 social) y Sector Standards (cada vez más sectores: carbón, agricultura, banca, oil & gas, minería...). Formato de 'material topics' con participación de stakeholders. Actualización 2021 con enfoque en impactos reales y derechos humanos. Convergencia activa con ESRS vía mapping EFRAG-GRI.",
    xrefRows: [
      { reportTitle: "EFRAG Sustainability Reporting Work Programme 2026", date: "12 feb 2026",
        criterionCa: "Mapping EFRAG-GRI actualitzat: 78% dels datapoints ESRS tenen equivalent en GRI. Reducció de treball duplicat per a empreses dual-reporting.",
        criterionEs: "Mapping EFRAG-GRI actualizado: 78% de los datapoints ESRS tienen equivalente en GRI. Reducción de trabajo duplicado para empresas dual-reporting.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD (Omnibus II)", date: "6 may 2026",
        criterionCa: "Simplificació ESRS facilita convergència amb GRI Topic Standards. Empreses amb GRI 2021 ben implementat tenen 60% del camí ESRS fet.",
        criterionEs: "Simplificación ESRS facilita convergencia con GRI Topic Standards. Empresas con GRI 2021 bien implementado tienen 60% del camino ESRS hecho.",
        impact: "high" },
      { reportTitle: "GRI Sector Standards: Oil & Gas 2026", date: "18 abr 2026",
        criterionCa: "Nou Sector Standard per a petroli i gas. Repsol, Cepsa, Naturgy afectades. 40+ datapoints específics sector.",
        criterionEs: "Nuevo Sector Standard para petróleo y gas. Repsol, Cepsa, Naturgy afectadas. 40+ datapoints específicos sector.",
        impact: "med" },
      { reportTitle: "GRI Biodiversity Standard 101 (2024)", date: "8 mar 2026",
        criterionCa: "Nou GRI 101: Biodiversitat. Alineat amb TNFD i GBF. Aplicable a sectors amb impacte directe (agro, mineria, fusta).",
        criterionEs: "Nuevo GRI 101: Biodiversidad. Alineado con TNFD y GBF. Aplicable a sectores con impacto directo (agro, minería, madera).",
        impact: "med" },
      { reportTitle: "GRI Climate Transition Plans (exposició)", date: "22 maig 2026",
        criterionCa: "Exposició pública de nou estàndard sobre plans de transició climàtica. Compatible amb TCFD, SBTi i ESRS E1.",
        criterionEs: "Exposición pública de nuevo estándar sobre planes de transición climática. Compatible con TCFD, SBTi y ESRS E1.",
        impact: "high" },
    ],
    actions: [
      { num: "1", textCa: "Mapejar material topics GRI existents amb datapoints ESRS via mapping EFRAG per identificar bretxes",
        textEs: "Mapear material topics GRI existentes con datapoints ESRS vía mapping EFRAG para identificar brechas",
        sourceCa: "Font: EFRAG Work Programme 2026", sourceEs: "Fuente: EFRAG Work Programme 2026" },
      { num: "2", textCa: "Preparar-se per a Sector Standards propers (Oil & Gas 2026, Mining 2027) amb gap analysis preliminar",
        textEs: "Prepararse para Sector Standards próximos (Oil & Gas 2026, Mining 2027) con gap analysis preliminar",
        sourceCa: "Font: GRI Sector Standards roadmap", sourceEs: "Fuente: GRI Sector Standards roadmap" },
      { num: "3", textCa: "Implementar GRI 101: Biodiversitat si el sector té impactes directes sobre ecosistemes",
        textEs: "Implementar GRI 101: Biodiversidad si el sector tiene impactos directos sobre ecosistemas",
        sourceCa: "Font: GRI Biodiversity Standard", sourceEs: "Fuente: GRI Biodiversity Standard" },
      { num: "4", textCa: "Participar en exposicions públiques GRI (Climate Transition Plans) per influir en el disseny final",
        textEs: "Participar en exposiciones públicas GRI (Climate Transition Plans) para influir en el diseño final",
        sourceCa: "Font: GRI public comment process", sourceEs: "Fuente: GRI public comment process" },
    ],
  },

  // ============================================================
  // 3. EcoVadis
  // ============================================================
  "ecovadis": {
    slug: "ecovadis",
    name: "EcoVadis",
    type: "cert",
    access: "premium",
    count: 5,
    logo: "/logos-estandards/ecovadis.jpg",
    issuerCa: "EcoVadis · París",
    issuerEs: "EcoVadis · París",
    descCa: "Rating de sostenibilitat corporativa amb metodologia pròpia basada en 21 criteris agrupats en 4 àrees: Environment, Labor & Human Rights, Ethics i Sustainable Procurement. Escala de medalla (Bronze, Silver, Gold, Platinum) sobre puntuació 0-100. El més demandat per cadenes de subministrament: 130.000+ empreses avaluades en 220 sectors i 175 països. Plataforma proprietària amb accés a scorecards dels proveïtors. Validació documental per analistes. Actualització anual. Cost per empresa: 1.500-15.000€ segons mida.",
    descEs: "Rating de sostenibilidad corporativa con metodología propia basada en 21 criterios agrupados en 4 áreas: Environment, Labor & Human Rights, Ethics y Sustainable Procurement. Escala de medalla (Bronze, Silver, Gold, Platinum) sobre puntuación 0-100. El más demandado por cadenas de suministro: 130.000+ empresas evaluadas en 220 sectores y 175 países. Plataforma propietaria con acceso a scorecards de proveedores. Validación documental por analistas. Actualización anual. Coste por empresa: 1.500-15.000€ según tamaño.",
    xrefRows: [
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "CSDDD demana due diligence en cadena de valor: EcoVadis és l'eina més usada per documentar compliance proveïdors.",
        criterionEs: "CSDDD pide due diligence en cadena de valor: EcoVadis es la herramienta más usada para documentar compliance proveedores.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD (Omnibus II)", date: "6 may 2026",
        criterionCa: "ESRS S1 (treballadors cadena valor) pot recolzar-se en scorecards EcoVadis com a evidència externa.",
        criterionEs: "ESRS S1 (trabajadores cadena valor) puede apoyarse en scorecards EcoVadis como evidencia externa.",
        impact: "med" },
      { reportTitle: "EcoVadis Platform Update 2026: Plata/Cards", date: "28 abr 2026",
        criterionCa: "Nous Platinum Action Plans amb correccions obligatòries. Redueix subjectivitat en medalla Platinum.",
        criterionEs: "Nuevos Platinum Action Plans con correcciones obligatorias. Reduce subjetividad en medalla Platinum.",
        impact: "med" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "Empreses subjectes a CSDDD han d'ampliar cobertura EcoVadis al 100% de proveïdors de risc (abans 80%).",
        criterionEs: "Empresas sujetas a CSDDD deben ampliar cobertura EcoVadis al 100% de proveedores de riesgo (antes 80%).",
        impact: "high" },
      { reportTitle: "SBTi Corporate Net-Zero Standard 2024", date: "10 feb 2026",
        criterionCa: "EcoVadis integra SBTi en criteri Environment. Empreses sense target SBTi no poden accedir a Gold/Platinum.",
        criterionEs: "EcoVadis integra SBTi en criterio Environment. Empresas sin target SBTi no pueden acceder a Gold/Platinum.",
        impact: "high" },
    ],
    actions: [
      { num: "1", textCa: "Ampliar cobertura EcoVadis al 100% de proveïdors de risc per comply amb CSDDD due diligence",
        textEs: "Ampliar cobertura EcoVadis al 100% de proveedores de riesgo para comply con CSDDD due diligence",
        sourceCa: "Font: CSDDD Omnibus I", sourceEs: "Fuente: CSDDD Omnibus I" },
      { num: "2", textCa: "Aconseguir target SBTi com a prereq per accedir a medalla Gold/Platinum en proper cicle",
        textEs: "Conseguir target SBTi como prereq para acceder a medalla Gold/Platinum en próximo ciclo",
        sourceCa: "Font: SBTi Corporate Net-Zero Standard", sourceEs: "Fuente: SBTi Corporate Net-Zero Standard" },
      { num: "3", textCa: "Usar scorecards EcoVadis com a evidència externa per a ESRS S1 (treballadors cadena valor)",
        textEs: "Usar scorecards EcoVadis como evidencia externa para ESRS S1 (trabajadores cadena valor)",
        sourceCa: "Font: ESRS S1 mapping", sourceEs: "Fuente: ESRS S1 mapping" },
      { num: "4", textCa: "Integrar Platinum Action Plans en el sistema de gestió intern per evitar pèrdua de medalla",
        textEs: "Integrar Platinum Action Plans en el sistema de gestión interno para evitar pérdida de medalla",
        sourceCa: "Font: EcoVadis Platform Update 2026", sourceEs: "Fuente: EcoVadis Platform Update 2026" },
    ],
  },

  // ============================================================
  // 4. B Corp (ja existent - ampliem xrefRows)
  // ============================================================
  "b-corp": {
    slug: "b-corp",
    name: "B Corp",
    type: "cert",
    access: "premium",
    count: 5,
    logo: "/logos-estandards/b-corp.svg",
    issuerCa: "B Lab Global · Estats Units",
    issuerEs: "B Lab Global · Estados Unidos",
    descCa: "Certificació d'empreses amb propòsit de B Lab. Avalua l'impacte positiu d'una empresa en treballadors, comunitat, entorn i clients mitjançant el B Impact Assessment (BIA): 250+ preguntes, score 0-200, mínim 80 per certificarse. 5 àrees: Governance, Workers, Community, Environment, Customers. 9.500+ empreses certificades a 100 països (400+ a Espanya, 5a comunitat mundial). Requereix modificación estatutària (compromís amb propòsit). Recertificació cada 3 anys. Nous estàndards B Lab 2026 amb performance requirements obligatoris alineats amb CSRD. Cost: 500-50.000€/any segons facturació.",
    descEs: "Certificación de empresas con propósito de B Lab. Evalúa el impacto positivo de una empresa en trabajadores, comunidad, entorno y clientes mediante el B Impact Assessment (BIA): 250+ preguntas, score 0-200, mínimo 80 para certificarse. 5 áreas: Governance, Workers, Community, Environment, Customers. 9.500+ empresas certificadas en 100 países (400+ en España, 5ª comunidad mundial). Requiere modificación estatutaria (compromiso con propósito). Recertificación cada 3 años. Nuevos estándares B Lab 2026 con performance requirements obligatorios alineados con CSRD. Coste: 500-50.000€/año según facturación.",
    xrefRows: [
      {
        reportTitle: "Revisió dels ESRS: simplificació del CSRD",
        reportSlug: "revisio-esrs-maig-2026",
        date: "6 may 2026",
        pillar: "Governance",
        subArea: "Mission & Engagement",
        criterionCa: "La simplificació de datapoints ESRS (de ~1.144 a ~600) redueix la càrrega de reporting paral·lel. B Lab evaluarà positivament empreses que demostrin reporting ESRS simplificat en lloc de sistemes duplicats.",
        criterionEs: "La simplificación de datapoints ESRS (de ~1.144 a ~600) reduce la carga de reporting paralelo. B Lab evaluará positivamente empresas que demuestren reporting ESRS simplificado en lugar de sistemas duplicados.",
        actionCa: "Mapeja els datapoints ESRS que ja tens amb les preguntes equivalents del BIA per evitar doble feina. Documenta el sistema únic de recollida de dades.",
        actionEs: "Mapea los datapoints ESRS que ya tienes con las preguntas equivalentes del BIA para evitar doble tarea. Documenta el sistema único de recogida de datos.",
        deadline: "Pròxima recertificació",
        impact: "med",
      },
      {
        reportTitle: "EFRAG Sustainability Reporting Work Programme 2026",
        reportSlug: "efrag-work-programme-2026",
        date: "12 feb 2026",
        pillar: "Governance",
        subArea: "Reporting & Transparency",
        criterionCa: "La convergència ESRS-GRI (78% dels datapoints equivalents) permet a les empreses B Corp reaprofitar el reporting GRI existent per a ambdós marcs. B Lab accepta GRI com a evidència complementària al BIA.",
        criterionEs: "La convergencia ESRS-GRI (78% de los datapoints equivalentes) permite a las empresas B Corp reaprovechar el reporting GRI existente para ambos marcos. B Lab acepta GRI como evidencia complementaria al BIA.",
        actionCa: "Identifica quins reports GRI 2021 ja tens implementats i marca'ls com a evidència directa per a les preguntes equivalents del BIA. Estalviaràs 30-40h de treball per cicle.",
        actionEs: "Identifica qué reports GRI 2021 ya tienes implementados y márcalos como evidencia directa para las preguntas equivalentes del BIA. Ahorrarás 30-40h de trabajo por ciclo.",
        deadline: "FY2026",
        impact: "high",
      },
      {
        reportTitle: "CSDDD Omnibus I: esmenes finals",
        reportSlug: "csddd-omnibus-març-2026",
        date: "15 mar 2026",
        pillar: "Community",
        subArea: "Human Rights & Supply Chain",
        criterionCa: "El deure de diligència en drets humans de CSDDD reforça directament el pilar 'Comunitat' del BIA. Les empreses amb sistema de queixes i mapa de riscos de proveïdors documentat poden puntuar més alt en les preguntes de 'Human Rights' i 'Supply Chain'.",
        criterionEs: "El deber de diligencia en derechos humanos de CSDDD refuerza directamente el pilar 'Comunidad' del BIA. Las empresas con sistema de quejas y mapa de riesgos de proveedores documentado pueden puntuar más alto en las preguntas de 'Human Rights' y 'Supply Chain'.",
        actionCa: "Implementa un sistema de queixes accessible (CSDDD Article 9) i documenta el mapa de riscos de la cadena de valor. Usa aquesta documentació com a evidència per al pilar Comunitat del BIA.",
        actionEs: "Implementa un sistema de quejas accesible (CSDDD Artículo 9) y documenta el mapa de riesgos de la cadena de valor. Usa esta documentación como evidencia para el pilar Comunidad del BIA.",
        deadline: "Q4 2026 (aplicació CSDDD)",
        impact: "high",
      },
      {
        reportTitle: "B Lab Standards V2.1: nova era per a B Corps",
        reportSlug: "bcorp-new-standards-2026",
        date: "22 abr 2026",
        pillar: "Governance",
        subArea: "Performance Requirements",
        criterionCa: "B Lab introdueix performance requirements obligatoris alineats amb CSRD. Les empreses existents han de fer gap analysis entre el BIA actual i els nous requirements abans de la recertificació. Risc de pèrdua de certificació si no es compleixen els mínims.",
        criterionEs: "B Lab introduce performance requirements obligatorios alineados con CSRD. Las empresas existentes deben hacer gap analysis entre el BIA actual y los nuevos requirements antes de la recertificación. Riesgo de pérdida de certificación si no se cumplen los mínimos.",
        actionCa: "Realitza una gap analysis entre els teus resultats BIA actuals i els nous performance requirements V2.1. Identifica les 3 àrees amb més bretxa i fes un pla d'acció de 6 mesos abans del proper cicle de verificació.",
        actionEs: "Realiza un gap analysis entre tus resultados BIA actuales y los nuevos performance requirements V2.1. Identifica las 3 áreas con más brecha y haz un plan de acción de 6 meses antes del próximo ciclo de verificación.",
        deadline: "Abans recertificació",
        impact: "high",
      },
      {
        reportTitle: "EU Taxonomy: Delegated Act de simplificació",
        reportSlug: "eu-taxonomy-delegated-act-2026",
        date: "28 mar 2026",
        pillar: "Environment",
        subArea: "Climate & Resources",
        criterionCa: "Les activitats alineades amb Taxonomia UE (cumplint contribució substancial + DNSH) serveixen com a evidència directa per a les preguntes del pilar 'Environment' del BIA, especialment en 'Climate Action' i 'Resource Use'.",
        criterionEs: "Las actividades alineadas con Taxonomía UE (cumpliendo contribución sustancial + DNSH) sirven como evidencia directa para las preguntas del pilar 'Environment' del BIA, especialmente en 'Climate Action' y 'Resource Use'.",
        actionCa: "Calcula els 3 KPIs Taxonomia (turnover, capex, opex) i mapeja les activitats alineades amb preguntes específiques del BIA Environment. Pot aportar 5-10 punts addicionals al score.",
        actionEs: "Calcula los 3 KPIs Taxonomía (turnover, capex, opex) y mapea las actividades alineadas con preguntas específicas del BIA Environment. Puede aportar 5-10 puntos adicionales al score.",
        deadline: "FY2026",
        impact: "med",
      },
    ],
    actions: [
      // NOTA: Les 'actions' genèriques per estàndard queden desaparegudes de la UI (recolzades però no mostrades).
      // El nou model integra l'acció concreta dins de cada xrefRow (camp 'action') perquè estigui vinculada
      // a un informe específic. Veure TASQUES.md — 'Accions recomanades' com a futura eina autònoma.
    ],
  },

  // ============================================================
  // 5. MSCI ESG
  // ============================================================
  "msci-esg": {
    slug: "msci-esg",
    name: "MSCI ESG",
    type: "cert",
    access: "premium",
    count: 5,
    logo: "/logos-estandards/msci-esg.svg",
    issuerCa: "MSCI Inc. · Nova York",
    issuerEs: "MSCI Inc. · Nueva York",
    descCa: "Rating ESG per a inversors amb escala AAA-CCC (líder, mitjà, retardatari). Avalua exposició a riscos ESG (10 temes, 35 categories) i gestió d'aquests riscos. Totes les cotitzades de l'IBEX 35 el monitoritzen. Impacte directe en cost de capital: un rating CCC pot augmentar el spread de deute 30-50 bp. Metodologia proprietària basada en dades públiques, disclosure de l'empresa i news screening. Actualització trimestral. MSCI també emet ratings de clima (TCFD-aligned), polèmiques i targetes de carboni. Competeix amb Sustainalytics i S&P Global ESG.",
    descEs: "Rating ESG para inversores con escala AAA-CCC (líder, medio, rezagado). Evalúa exposición a riesgos ESG (10 temas, 35 categorías) y gestión de esos riesgos. Todas las cotizadas del IBEX 35 lo monitorizan. Impacto directo en coste de capital: un rating CCC puede aumentar el spread de deuda 30-50 bp. Metodología propietaria basada en datos públicos, disclosure de la empresa y news screening. Actualización trimestral. MSCI también emite ratings de clima (TCFD-aligned), controversias y huellas de carbono. Compite con Sustainalytics y S&P Global ESG.",
    xrefRows: [
      { reportTitle: "MSCI Climate Methodology Update 2026", date: "15 mar 2026",
        criterionCa: "Nous criteris per a Implied Temperature Rise (ITR). Empreses >2,5°C perden automaticament AAA.",
        criterionEs: "Nuevos criterios para Implied Temperature Rise (ITR). Empresas >2,5°C pierden automáticamente AAA.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "ESRS E1 reporting alimentarà directament dades MSCI Climate. Empreses ESRS-compliant veuran millora en ITR.",
        criterionEs: "ESRS E1 reporting alimentará directamente datos MSCI Climate. Empresas ESRS-compliant verán mejora en ITR.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "MSCI integra dades CSDDD due diligence en pilar 'Social'. Descàrrec en CSDDD pot rebaixar rating 1 notch.",
        criterionEs: "MSCI integra datos CSDDD due diligence en pilar 'Social'. Descuido en CSDDD puede bajar rating 1 notch.",
        impact: "med" },
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "MSCI pondera Taxonomia UE alineació en score 'Green Opportunities'. Activitats alineades milloren rating.",
        criterionEs: "MSCI pondera Taxonomía UE alineación en score 'Green Opportunities'. Actividades alineadas mejoran rating.",
        impact: "med" },
      { reportTitle: "SBTi Corporate Net-Zero Standard 2024", date: "10 feb 2026",
        criterionCa: "MSCI penalitza empreses sense target SBTi verificat: -1 notch en rating Climate.",
        criterionEs: "MSCI penaliza empresas sin target SBTi verificado: -1 notch en rating Climate.",
        impact: "high" },
    ],
    actions: [
      { num: "1", textCa: "Auditar la metodologia MSCI per als 10 temes materials i assegurar disclosure públic suficient",
        textEs: "Auditar la metodología MSCI para los 10 temas materiales y asegurar disclosure público suficiente",
        sourceCa: "Font: MSCI ESG Ratings Methodology", sourceEs: "Fuente: MSCI ESG Ratings Methodology" },
      { num: "2", textCa: "Implementar target SBTi verificat per evitar penalització -1 notch en Climate rating",
        textEs: "Implementar target SBTi verificado para evitar penalización -1 notch en Climate rating",
        sourceCa: "Font: SBTi Corporate Net-Zero Standard", sourceEs: "Fuente: SBTi Corporate Net-Zero Standard" },
      { num: "3", textCa: "Monitoritzar Implied Temperature Rise (ITR) i accions correctores si supera 2,0°C",
        textEs: "Monitorizar Implied Temperature Rise (ITR) y acciones correctoras si supera 2,0°C",
        sourceCa: "Font: MSCI Climate Methodology 2026", sourceEs: "Fuente: MSCI Climate Methodology 2026" },
      { num: "4", textCa: "Mantenir diàleg actiu amb MSCI ESG Research per corregir errors en dades i controversias",
        textEs: "Mantener diálogo activo con MSCI ESG Research para corregir errores en datos y controversias",
        sourceCa: "Font: MSCI Issuer Communication Protocol", sourceEs: "Fuente: MSCI Issuer Communication Protocol" },
    ],
  },

  // ============================================================
  // 6. CSDDD
  // ============================================================
  "csddd": {
    slug: "csddd",
    name: "CSDDD",
    type: "reg",
    access: "free",
    count: 5,
    logo: "/logos-estandards/csddd.png",
    issuerCa: "Comissió Europea · DG Justice",
    issuerEs: "Comisión Europea · DG Justice",
    descCa: "Directiva (UE) 2024/1760 de due diligence en drets humans i sostenibilitat. Obliga empreses a identificar, prevenir, mitigar i explicar impactes adversos en drets humans i medi ambient a la seva cadena de valor. Àmbit: empreses UE >1.000 empleats i >450M€ facturació (després de l'Omnibus I, ~5.200 empreses vs 13.000 inicials). Aplicació escalonada 2027-2029 segons mida. Inclou pla de transició climàtica alineat amb 1,5°C. Sancions fins al 5% de facturació neta mundial. Transposició als estats membres obligatòria abans juliol 2026.",
    descEs: "Directiva (UE) 2024/1760 de due diligence en derechos humanos y sostenibilidad. Obliga a empresas a identificar, prevenir, mitigar y explicar impactes adversos en derechos humanos y medio ambiente en su cadena de valor. Ámbito: empresas UE >1.000 empleados y >450M€ facturación (tras Omnibus I, ~5.200 empresas vs 13.000 iniciales). Aplicación escalonada 2027-2029 según tamaño. Incluye plan de transición climática alineado con 1,5°C. Sanciones hasta el 5% de facturación neta mundial. Transposición a estados miembros obligatoria antes de julio 2026.",
    xrefRows: [
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "Reducció d'empreses afectades de 13.000 a 5.200. Llindar pujat a 1.000 empleats i 450M€ facturació.",
        criterionEs: "Reducción de empresas afectadas de 13.000 a 5.200. Umbral subido a 1.000 empleados y 450M€ facturación.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus II: clima i transposició", date: "20 maig 2026",
        criterionCa: "Pla de transició climàtica alineat amb 1,5°C obligatori. Compatible amb ESRS E1 i TCFD.",
        criterionEs: "Plan de transición climática alineado con 1,5°C obligatorio. Compatible con ESRS E1 y TCFD.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "ESRS S1 i S2 s'alineen amb CSDDD: una sola due diligence pot servir per a ambdós.",
        criterionEs: "ESRS S1 y S2 se alinean con CSDDD: una sola due diligence puede servir para ambos.",
        impact: "med" },
      { reportTitle: "Transposició CSDDD Espanya: esborrany Ministeri", date: "30 abr 2026",
        criterionCa: "Espanya prepara transposició amb sancions addicionals: fins a 10M€ per infraccions greus.",
        criterionEs: "España prepara transposición con sanciones adicionales: hasta 10M€ por infracciones graves.",
        impact: "high" },
      { reportTitle: "EFRAG Sustainability Reporting Work Programme 2026", date: "12 feb 2026",
        criterionCa: "EFRAG publica guia pràctica per integrar CSDDD due diligence en reporting ESRS.",
        criterionEs: "EFRAG publica guía práctica para integrar CSDDD due diligence en reporting ESRS.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Mapejar cadena de valor completa (Tier 1-3) i identificar hotspots de risc en drets humans",
        textEs: "Mapear cadena de valor completa (Tier 1-3) e identificar hotspots de riesgo en derechos humanos",
        sourceCa: "Font: CSDDD Annex I", sourceEs: "Fuente: CSDDD Annex I" },
      { num: "2", textCa: "Dissenyar pla de transició climàtica 1,5°C compatible amb ESRS E1 i TCFD",
        textEs: "Diseñar plan de transición climática 1,5°C compatible con ESRS E1 y TCFD",
        sourceCa: "Font: CSDDD Article 22", sourceEs: "Fuente: CSDDD Article 22" },
      { num: "3", textCa: "Implementar sistema de queixes (complaint mechanism) accessible a treballadors i comunitats afectades",
        textEs: "Implementar sistema de quejas (complaint mechanism) accesible a trabajadores y comunidades afectadas",
        sourceCa: "Font: CSDDD Article 9", sourceEs: "Fuente: CSDDD Article 9" },
      { num: "4", textCa: "Monitoritzar procés transposició Espanya per preparar compliance amb sancions nacionals",
        textEs: "Monitorizar proceso transposición España para preparar compliance con sanciones nacionales",
        sourceCa: "Font: Esborrany Ministeri 2026", sourceEs: "Fuente: Borrador Ministerio 2026" },
    ],
  },

  // ============================================================
  // 7. SFDR
  // ============================================================
  "sfdr": {
    slug: "sfdr",
    name: "SFDR",
    type: "reg",
    access: "free",
    count: 4,
    logo: "/logos-estandards/sfdr.png",
    issuerCa: "Comissió Europea · DG FISMA",
    issuerEs: "Comisión Europea · DG FISMA",
    descCa: "Reglament (UE) 2019/2088 de divulgació de finances sostenibles. Classifica productes financers en 3 categories: Article 6 (no sostenible), Article 8 ('light green', promou ESG) i Article 9 ('dark green', objectiu sostenible explícit). Obliga gestores, bancs i asseguradores a publicar PAI (Principal Adverse Impacts) i declaracions precontractuals. Afecta ~12.000 fons europeus. En revisió: la ESA proposa nova categorització (sustainable, transition, ESG collection) per evitar greenwashing. Entrada en vigor complet 2023, però RTS i plantilles electròniques encara en evolució.",
    descEs: "Reglamento (UE) 2019/2088 de divulgación de finanzas sostenibles. Clasifica productos financieros en 3 categorías: Artículo 6 (no sostenible), Artículo 8 ('light green', promueve ESG) y Artículo 9 ('dark green', objetivo sostenible explícito). Obliga a gestoras, bancos y aseguradoras a publicar PAI (Principal Adverse Impacts) y declaraciones precontractuales. Afecta a ~12.000 fondos europeos. En revisión: la ESA propone nueva categorización (sustainable, transition, ESG collection) para evitar greenwashing. Entrada en vigor completa 2023, pero RTS y plantillas electrónicas aún en evolución.",
    xrefRows: [
      { reportTitle: "SFDR Review 2026: nova categorització ESA", date: "18 mar 2026",
        criterionCa: "ESA proposa reclassificació: sustainable, transition, ESG collection. Fi d'Articles 8 i 9 actuals.",
        criterionEs: "ESA propone reclasificación: sustainable, transition, ESG collection. Fin de Artículos 8 y 9 actuales.",
        impact: "high" },
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "Fons Article 9 han de tenir 100% d'inversions alineades amb Taxonomia UE. Nous criteris tècnics.",
        criterionEs: "Fondos Artículo 9 deben tener 100% de inversiones alineadas con Taxonomía UE. Nuevos criterios técnicos.",
        impact: "high" },
      { reportTitle: "ESMA Sustainable Finance Q&A 2026", date: "5 abr 2026",
        criterionCa: "ESMA clarifica: 'sustainable investment' requereix 'do no significant harm' verificat, no només declarat.",
        criterionEs: "ESMA clarifica: 'sustainable investment' requiere 'do no significant harm' verificado, no solo declarado.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "Dades ESRS alimenten PAI indicators SFDR. Reducció datapoints ESRS facilita reporting PAI.",
        criterionEs: "Datos ESRS alimentan PAI indicators SFDR. Reducción datapoints ESRS facilita reporting PAI.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Revisar classificació Article 8/9 de la cartera a la llum de la nova categorització ESA",
        textEs: "Revisar clasificación Artículo 8/9 de la cartera a la luz de la nueva categorización ESA",
        sourceCa: "Font: SFDR Review 2026", sourceEs: "Fuente: SFDR Review 2026" },
      { num: "2", textCa: "Auditar 'do no significant harm' dels fons Article 9 amb dades verificables externes",
        textEs: "Auditar 'do no significant harm' de los fondos Artículo 9 con datos verificables externos",
        sourceCa: "Font: ESMA Sustainable Finance Q&A", sourceEs: "Fuente: ESMA Sustainable Finance Q&A" },
      { num: "3", textCa: "Preparar migració de plantilles precontractuals al nou format electrònic ESA (Q4 2026)",
        textEs: "Preparar migración de plantillas precontractuales al nuevo formato electrónico ESA (Q4 2026)",
        sourceCa: "Font: SFDR RTS amendment", sourceEs: "Fuente: SFDR RTS amendment" },
      { num: "4", textCa: "Integrar dades ESRS d'inversions en PAI indicators per evitar doble treball",
        textEs: "Integrar datos ESRS de inversiones en PAI indicators para evitar doble trabajo",
        sourceCa: "Font: EFRAG-SFDR mapping", sourceEs: "Fuente: EFRAG-SFDR mapping" },
    ],
  },

  // ============================================================
  // 8. Taxonomia UE
  // ============================================================
  "taxonomia-ue": {
    slug: "taxonomia-ue",
    name: "Taxonomía UE",
    type: "reg",
    access: "free",
    count: 5,
    logo: "/logos-estandards/taxonomia-ue.png",
    issuerCa: "Comissió Europea · DG FISMA",
    issuerEs: "Comisión Europea · DG FISMA",
    descCa: "Reglament (UE) 2020/852 que classifica activitats econòmiques com a sostenibles. Defineix què és 'verd' amb criteris tècnics de pantalla (Technical Screening Criteria) per a 6 objectius ambientals: mitigació climàtica, adaptació, aigua, economia circular, contaminació, biodiversitat. Una activitat és alineada si compleix 3 condicions: contribució substancial, no fer mal significatiu (DNSH) i garanties mínimes socials. Actualment amb Delegated Acts per clima (2021), complementari (2022) i mediambiental (2023). Pendents: criteris per a transició (gas, nuclear en debat) i objectius socials.",
    descEs: "Reglamento (UE) 2020/852 que clasifica actividades económicas como sostenibles. Define qué es 'verde' con criterios técnicos de pantalla (Technical Screening Criteria) para 6 objetivos ambientales: mitigación climática, adaptación, agua, economía circular, contaminación, biodiversidad. Una actividad está alineada si cumple 3 condiciones: contribución sustancial, no hacer daño significativo (DNSH) y garantías mínimas sociales. Actualmente con Delegated Acts para clima (2021), complementario (2022) y medioambiental (2023). Pendientes: criterios para transición (gas, nuclear en debate) y objetivos sociales.",
    xrefRows: [
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "Nous criteris per a 4 sectors manufacturers i transport marítim. ~30 activitats noves afegides.",
        criterionEs: "Nuevos criterios para 4 sectores manufactureros y transporte marítimo. ~30 actividades nuevas añadidas.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "ESRS E5 (economia circular) s'alinea amb Taxonomia UE. Empreses poden usar dades Taxonomia com a evidència ESRS.",
        criterionEs: "ESRS E5 (economía circular) se alinea con Taxonomía UE. Empresas pueden usar datos Taxonomía como evidencia ESRS.",
        impact: "med" },
      { reportTitle: "Taxonomia Social: esborrany Platform on Sustainable Finance", date: "12 abr 2026",
        criterionCa: "Platform publica esborrany de criteris per als objectius socials (4a onada). Consulta pública fins setembre 2026.",
        criterionEs: "Platform publica borrador de criterios para los objetivos sociales (4ª ola). Consulta pública hasta septiembre 2026.",
        impact: "high" },
      { reportTitle: "SFDR Review 2026: nova categorització ESA", date: "18 mar 2026",
        criterionCa: "Fons Article 9 requereixen 100% alineació Taxonomia. Pressió sobre gestores per reclassificar.",
        criterionEs: "Fondos Artículo 9 requieren 100% alineación Taxonomía. Presión sobre gestoras para reclasificar.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus II: clima i transposició", date: "20 maig 2026",
        criterionCa: "Activitats alineades amb Taxonomia compleixen automàticament part del pla de transició 1,5°C CSDDD.",
        criterionEs: "Actividades alineadas con Taxonomía cumplen automáticamente parte del plan de transición 1,5°C CSDDD.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Mapejar activitats pròpies amb els nous criteris del Delegated Act 2026 per identificar alineació",
        textEs: "Mapear actividades propias con los nuevos criterios del Delegated Act 2026 para identificar alineación",
        sourceCa: "Font: EU Taxonomy Delegated Act 2026", sourceEs: "Fuente: EU Taxonomy Delegated Act 2026" },
      { num: "2", textCa: "Calcular els 3 KPIs Taxonomia (turnover, capex, opex) amb metodologia consistent any rere any",
        textEs: "Calcular los 3 KPIs Taxonomía (turnover, capex, opex) con metodología consistente año tras año",
        sourceCa: "Font: Disclosure Delegated Act Article 8", sourceEs: "Fuente: Disclosure Delegated Act Article 8" },
      { num: "3", textCa: "Participar en consulta pública Taxonomia Social per influir en futurs criteris",
        textEs: "Participar en consulta pública Taxonomía Social para influir en futuros criterios",
        sourceCa: "Font: Platform on Sustainable Finance", sourceEs: "Fuente: Platform on Sustainable Finance" },
      { num: "4", textCa: "Verificar 'do no significant harm' i garanties mínimes socials per cada activitat alineada",
        textEs: "Verificar 'do no significant harm' y garantías mínimas sociales para cada actividad alineada",
        sourceCa: "Font: Taxonomy Regulation Article 17", sourceEs: "Fuente: Taxonomy Regulation Article 17" },
    ],
  },

  // ============================================================
  // 9. CDP
  // ============================================================
  "cdp": {
    slug: "cdp",
    name: "CDP",
    type: "cert",
    access: "premium",
    count: 4,
    logo: "/logos-estandards/cdp.png",
    issuerCa: "CDP · Londres",
    issuerEs: "CDP · Londres",
    descCa: "Sistema global de disclosure ambiental per a clima, aigua i boscos. Les empreses responen qüestionaris anuals estandarditzats (TCFD-aligned des de 2018) i reben puntuació A- a D- basada en comprehensivitat i transparència, no en performance. 24.000+ empreses responen (cobrint 66% de la capitalització global). Usat per 740+ inversors amb 136 trilions $ en actius i compradors corporatius. Dades públiques a la plataforma CDP. Gratuito per respondre, però accés a scorecards de tercers és de pagament. Integrat amb SBTi i CDP-targets verify net-zero pathways.",
    descEs: "Sistema global de divulgación ambiental para clima, agua y bosques. Las empresas responden cuestionarios anuales estandarizados (TCFD-aligned desde 2018) y reciben puntuación A- a D- basada en comprehensividad y transparencia, no en performance. 24.000+ empresas responden (cubriendo 66% de la capitalización global). Usado por 740+ inversores con 136 trillones $ en activos y compradores corporativos. Datos públicos en la plataforma CDP. Gratuito para responder, pero acceso a scorecards de terceros es de pago. Integrado con SBTi y CDP-targets verify net-zero pathways.",
    xrefRows: [
      { reportTitle: "CDP Technical Note 2026: ESRS E1 alignment", date: "10 abr 2026",
        criterionCa: "CDP actualitza qüestionari Climate per alinear-se amb ESRS E1. 80% de preguntes CDP ja són ESRS-compliant.",
        criterionEs: "CDP actualiza cuestionario Climate para alinearse con ESRS E1. 80% de preguntas CDP ya son ESRS-compliant.",
        impact: "high" },
      { reportTitle: "SBTi Corporate Net-Zero Standard 2024", date: "10 feb 2026",
        criterionCa: "CDP requereix disclosure SBTi targets en qüestionari Climate. Sense SBTi, màxima puntuació B.",
        criterionEs: "CDP requiere disclosure SBTi targets en cuestionario Climate. Sin SBTi, máxima puntuación B.",
        impact: "high" },
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "CDP Water Scorecard integra criteris Taxonomia UE per a activitats hídriques. Nou mòdul obligatori.",
        criterionEs: "CDP Water Scorecard integra criterios Taxonomía UE para actividades hídricas. Nuevo módulo obligatorio.",
        impact: "med" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "Simplificació ESRS facilita mapping amb CDP. Redueix duplicitat de disclosure climàtic.",
        criterionEs: "Simplificación ESRS facilita mapping con CDP. Reduce duplicidad de disclosure climático.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Aprofitar alineació CDP-ESRS E1 per respondre una sola vegada i alimentar dos frameworks",
        textEs: "Aprovechar alineación CDP-ESRS E1 para responder una sola vez y alimentar dos frameworks",
        sourceCa: "Font: CDP Technical Note 2026", sourceEs: "Fuente: CDP Technical Note 2026" },
      { num: "2", textCa: "Establir target SBTi verificat per optar a puntuació A en proper cicle CDP",
        textEs: "Establecer target SBTi verificado para optar a puntuación A en próximo ciclo CDP",
        sourceCa: "Font: SBTi Corporate Net-Zero Standard", sourceEs: "Fuente: SBTi Corporate Net-Zero Standard" },
      { num: "3", textCa: "Respondre qüestionari CDP Water amb dades Taxonomia UE per activitats hídriques",
        textEs: "Responder cuestionario CDP Water con datos Taxonomía UE para actividades hídricas",
        sourceCa: "Font: CDP Water Scorecard 2026", sourceEs: "Fuente: CDP Water Scorecard 2026" },
      { num: "4", textCa: "Mantenir consistència temporal de dades CDP amb reporting ESRS per evitar contradiccions",
        textEs: "Mantener consistencia temporal de datos CDP con reporting ESRS para evitar contradicciones",
        sourceCa: "Font: ESRS E1-CDP mapping", sourceEs: "Fuente: ESRS E1-CDP mapping" },
    ],
  },

  // ============================================================
  // 10. SGE 21
  // ============================================================
  "sge-21": {
    slug: "sge-21",
    name: "SGE 21",
    type: "cert",
    access: "premium",
    count: 4,
    logo: "/logos-estandards/sge-21.svg",
    issuerCa: "Forética · Madrid",
    issuerEs: "Forética · Madrid",
    descCa: "Sistema de Gestió Ètica i Socialment Responsible, gestionat per Forética (2000). Únic estàndard ESG desenvolupat a Espanya i certificable per tercera part (auditoria externa anual). Alineat amb ISO 26000, ISO 9001, UNE 165002, GRI i SDGs. 4 àrees: estratègia i govern, recursos humans, proveïdors i aliances, i transparència i rendició de comptes. 350+ empreses certificades a Espanya i Llatinoamèrica (Ferrovial, Repsol, Bankinter, Vodafone España, Mapfre). Compatible amb doble materialitat CSRD. Renovació anual amb auditoria de seguiment.",
    descEs: "Sistema de Gestión Ética y Socialmente Responsable, gestionado por Forética (2000). Único estándar ESG desarrollado en España y certificable por tercera parte (auditoría externa anual). Alineado con ISO 26000, ISO 9001, UNE 165002, GRI y SDGs. 4 áreas: estrategia y gobierno, recursos humanos, proveedores y alianzas, y transparencia y rendición de cuentas. 350+ empresas certificadas en España y Latinoamérica (Ferrovial, Repsol, Bankinter, Vodafone España, Mapfre). Compatible con doble materialidad CSRD. Renovación anual con auditoría de seguimiento.",
    xrefRows: [
      { reportTitle: "Forética SGE 21: actualització 2026 alineada amb CSRD", date: "5 mar 2026",
        criterionCa: "Forética publica versió 2026 amb nous requisits alineats amb ESRS. Auditoria per doble materialitat.",
        criterionEs: "Forética publica versión 2026 con nuevos requisitos alineados con ESRS. Auditoría por doble materialidad.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "SGE 21 pot servir com a evidència externa de due diligence per a CSDDD en cadena de valor.",
        criterionEs: "SGE 21 puede servir como evidencia externa de due diligence para CSDDD en cadena de valor.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "SGE 21 actualitza requisits de transparència per alinear-se amb datapoints ESRS simplificats.",
        criterionEs: "SGE 21 actualiza requisitos de transparencia para alinearse con datapoints ESRS simplificados.",
        impact: "med" },
      { reportTitle: "Forética Generación Sostenible 2026", date: "20 abr 2026",
        criterionCa: "Informe Forética identifica SGE 21 com a eina clau per a pimes espanyoles preparant CSRD.",
        criterionEs: "Informe Forética identifica SGE 21 como herramienta clave para pymes españolas preparando CSRD.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Migrar a versió SGE 21:2026 abans de la propera auditoria per mantenir certificació vigent",
        textEs: "Migrar a versión SGE 21:2026 antes de la próxima auditoría para mantener certificación vigente",
        sourceCa: "Font: Forética SGE 21:2026", sourceEs: "Fuente: Forética SGE 21:2026" },
      { num: "2", textCa: "Documentar due diligence cadena valor per usar SGE 21 com a evidència CSDDD",
        textEs: "Documentar due diligence cadena valor para usar SGE 21 como evidencia CSDDD",
        sourceCa: "Font: CSDDD Omnibus I", sourceEs: "Fuente: CSDDD Omnibus I" },
      { num: "3", textCa: "Aprofitar auditoria SGE 21 per preparar evidències ESRS (governança, transparència)",
        textEs: "Aprovechar auditoría SGE 21 para preparar evidencias ESRS (gobernanza, transparencia)",
        sourceCa: "Font: ESRS-SGE 21 mapping", sourceEs: "Fuente: ESRS-SGE 21 mapping" },
      { num: "4", textCa: "Integrar el sistema SGE 21 amb ISO 26000 per a una visió unificada de responsabilitat social",
        textEs: "Integrar el sistema SGE 21 con ISO 26000 para una visión unificada de responsabilidad social",
        sourceCa: "Font: ISO 26000:2010 + SGE 21:2026", sourceEs: "Fuente: ISO 26000:2010 + SGE 21:2026" },
    ],
  },

  // ============================================================
  // 11. Sustainalytics
  // ============================================================
  "sustainalytics": {
    slug: "sustainalytics",
    name: "Sustainalytics",
    type: "cert",
    access: "premium",
    count: 4,
    logo: "/logos-estandards/sustainalytics.svg",
    issuerCa: "Morningstar Sustainalytics · Amsterdam",
    issuerEs: "Morningstar Sustainalytics · Ámsterdam",
    descCa: "Rating de risc ESG per a inversors, ara propietat de Morningstar. Escala de 5 nivells: Negligible, Low, Medium, High, Severe (sobre puntuació 0-100 invertida). Diferent de MSCI: avalua risc financer no gestionat, no performance. Cobertura: 13.000+ empreses globals. Productes: ESG Risk Ratings (core), Country Risk, Controversies, Carbon Risk Ratings, Low Carbon Transition Ratings. Usat per identificar underpriced risk en renda variable i fixa. Les dades alimenten índexs Morningstar. Plataforma Moodys ESG fusionada amb Sustainalytics el 2022.",
    descEs: "Rating de riesgo ESG para inversores, ahora propiedad de Morningstar. Escala de 5 niveles: Negligible, Low, Medium, High, Severe (sobre puntuación 0-100 invertida). Diferente de MSCI: evalúa riesgo financiero no gestionado, no performance. Cobertura: 13.000+ empresas globales. Productos: ESG Risk Ratings (core), Country Risk, Controversies, Carbon Risk Ratings, Low Carbon Transition Ratings. Usado para identificar underpriced risk en renta variable y fija. Los datos alimentan índices Morningstar. Plataforma Moodys ESG fusionada con Sustainalytics en 2022.",
    xrefRows: [
      { reportTitle: "Sustainalytics Methodology Update 2026", date: "8 abr 2026",
        criterionCa: "Nous factors de risc per a CSDDD due diligence. Empreses sense DD completen reben 20 punts de risc addicional.",
        criterionEs: "Nuevos factores de riesgo para CSDDD due diligence. Empresas sin DD completan reciben 20 puntos de riesgo adicional.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "Sustainalytics usa dades ESRS per alimentar scorecards. Reducció datapoints facilita cobertura.",
        criterionEs: "Sustainalytics usa datos ESRS para alimentar scorecards. Reducción datapoints facilita cobertura.",
        impact: "med" },
      { reportTitle: "Morningstar Low Carbon Transition Ratings 2026", date: "12 mar 2026",
        criterionCa: "Sustainalytics publica LCTR amb Implied Temperature Score. Empreses >2,5°C reben High Risk.",
        criterionEs: "Sustainalytics publica LCTR con Implied Temperature Score. Empresas >2,5°C reciben High Risk.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "Sustainalytics integra compliance CSDDD en pilar 'Social'. Sense DD, màxim rating Medium.",
        criterionEs: "Sustainalytics integra compliance CSDDD en pilar 'Social'. Sin DD, máximo rating Medium.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Implementar due diligence CSDDD per evitar 20 punts addicionals de risc en scorecard",
        textEs: "Implementar due diligence CSDDD para evitar 20 puntos adicionales de riesgo en scorecard",
        sourceCa: "Font: Sustainalytics Methodology 2026", sourceEs: "Fuente: Sustainalytics Methodology 2026" },
      { num: "2", textCa: "Monitoritzar Implied Temperature Score per mantenir-lo per sota de 2,0°C",
        textEs: "Monitorizar Implied Temperature Score para mantenerlo por debajo de 2,0°C",
        sourceCa: "Font: Morningstar LCTR 2026", sourceEs: "Fuente: Morningstar LCTR 2026" },
      { num: "3", textCa: "Comunicar proactivament amb Sustainalytics per corregir errors en dades empresarials",
        textEs: "Comunicar proactivamente con Sustainalytics para corregir errores en datos empresariales",
        sourceCa: "Font: Sustainalytics Issuer Portal", sourceEs: "Fuente: Sustainalytics Issuer Portal" },
      { num: "4", textCa: "Aprofitar dades ESRS per alimentar scorecard Sustainalytics sense duplicitat de treball",
        textEs: "Aprovechar datos ESRS para alimentar scorecard Sustainalytics sin duplicidad de trabajo",
        sourceCa: "Font: ESRS-Sustainalytics mapping", sourceEs: "Fuente: ESRS-Sustainalytics mapping" },
    ],
  },

  // ============================================================
  // 12. SASB
  // ============================================================
  "sasb": {
    slug: "sasb",
    name: "SASB",
    type: "fw",
    access: "free",
    count: 4,
    logo: "/logos-estandards/sasb.png",
    issuerCa: "IFRS Foundation · ISSB",
    issuerEs: "IFRS Foundation · ISSB",
    descCa: "Sustainability Accounting Standards Board, ara integrat a l'ISSB (IFRS Sustainability Disclosure Standards). Estàndards de reporting financer-sostenibilitat per sector: 77 indústries amb ~13 temes materials cadascun. Enfocament en 'financial materiality' (una sola materialitat, contraposat a la doble materialitat de CSRD). Dades quantitatives orientades a inversors. Ús en creixement: 1.300+ empreses globals reporten amb SASB. Base de l'S2 (climate disclosure) de l'ISSB. Compatible amb TCFD i GRI. Materials gratuitament; certificación obligatòria per a reports públics.",
    descEs: "Sustainability Accounting Standards Board, ahora integrado en el ISSB (IFRS Sustainability Disclosure Standards). Estándares de reporting financero-sostenibilidad por sector: 77 industrias con ~13 temas materiales cada una. Enfoque en 'financial materiality' (una sola materialidad, contrapuesto a la doble materialidad de CSRD). Datos cuantitativos orientados a inversores. Uso en crecimiento: 1.300+ empresas globales reportan con SASB. Base del S2 (climate disclosure) del ISSB. Compatible con TCFD y GRI. Materiales gratuitos; certificación obligatoria para reports públicos.",
    xrefRows: [
      { reportTitle: "ISSB S2 (Climate) Implementation Update 2026", date: "28 mar 2026",
        criterionCa: "ISSB S2 entra en vigor FY2025. Basat en SASB + TCFD. Empreses amb SASB ja implementat tenen 70% del camí fet.",
        criterionEs: "ISSB S2 entra en vigor FY2025. Basado en SASB + TCFD. Empresas con SASB ya implementado tienen 70% del camino hecho.",
        impact: "high" },
      { reportTitle: "ISSB-SASB Sector Standards Update 2026", date: "15 abr 2026",
        criterionCa: "ISSB publica nous sector standards basats en SASB. Primers: financials, materials, tecnologia.",
        criterionEs: "ISSB publica nuevos sector standards basados en SASB. Primeros: financials, materiales, tecnología.",
        impact: "med" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "SASB (financial materiality) i ESRS (doble materialitat) són complementaris. Mapping disponible.",
        criterionEs: "SASB (financial materiality) y ESRS (doble materialidad) son complementarios. Mapping disponible.",
        impact: "med" },
      { reportTitle: "EFRAG Sustainability Reporting Work Programme 2026", date: "12 feb 2026",
        criterionCa: "EFRAG i ISSB publiquen conjuntament mapping ESRS-ISSB per facilitar dual-reporting.",
        criterionEs: "EFRAG e ISSB publican conjuntamente mapping ESRS-ISSB para facilitar dual-reporting.",
        impact: "high" },
    ],
    actions: [
      { num: "1", textCa: "Mapejar SASB metrics existents amb ISSB S2 per implementar compliance amb menys esforç",
        textEs: "Mapear SASB metrics existentes con ISSB S2 para implementar compliance con menos esfuerzo",
        sourceCa: "Font: ISSB S2 Implementation", sourceEs: "Fuente: ISSB S2 Implementation" },
      { num: "2", textCa: "Identificar sector SASB aplicable i revisar temes materials actualitzats (2026)",
        textEs: "Identificar sector SASB aplicable y revisar temas materiales actualizados (2026)",
        sourceCa: "Font: SASB Sector Standards", sourceEs: "Fuente: SASB Sector Standards" },
      { num: "3", textCa: "Usar mapping ESRS-ISSB per reporting dual sense duplicitat",
        textEs: "Usar mapping ESRS-ISSB para reporting dual sin duplicidad",
        sourceCa: "Font: EFRAG-ISSB mapping 2026", sourceEs: "Fuente: EFRAG-ISSB mapping 2026" },
      { num: "4", textCa: "Prioritzar dades quantitatives SASB per a inversors (vs dades qualitatives ESRS per a stakeholders amplis)",
        textEs: "Priorizar datos cuantitativos SASB para inversores (vs datos cualitativos ESRS para stakeholders amplios)",
        sourceCa: "Font: SASB Conceptual Framework", sourceEs: "Fuente: SASB Conceptual Framework" },
    ],
  },

  // ============================================================
  // 13. TNFD
  // ============================================================
  "tnfd": {
    slug: "tnfd",
    name: "TNFD",
    type: "fw",
    access: "free",
    count: 4,
    logo: "/logos-estandards/tnfd.png",
    issuerCa: "Taskforce on Nature-related Financial Disclosures",
    issuerEs: "Taskforce on Nature-related Financial Disclosures",
    descCa: "Framework global per reportar dependències, impactes, riscos i oportunitats relacionats amb la natura. Llançat el setembre 2023 amb 14 recomanacions estructurals (4 pilars: governance, strategy, risk & impact management, metrics & targets). Complementa TCFD enfocant-se en biodiversitat, ecosistemes i serveis ecosistèmics. Eines: LEAP approach (Locate, Evaluate, Assess, Prepare) per a autoavaluació. 500+ early adopters globales. Base probable per a futurs estàndards ESRS E4 (biodiversitat) i ISSB sobre natura. Suport dels estats del GBF (Kunming-Montreal 2022).",
    descEs: "Framework global para reportar dependencias, impactos, riesgos y oportunidades relacionados con la naturaleza. Lanzado en septiembre 2023 con 14 recomendaciones estructurales (4 pilares: governance, strategy, risk & impact management, metrics & targets). Complementa a TCFD enfocándose en biodiversidad, ecosistemas y servicios ecosistémicos. Herramientas: LEAP approach (Locate, Evaluate, Assess, Prepare) para autoevaluación. 500+ early adopters globales. Base probable para futuros estándares ESRS E4 (biodiversidad) e ISSB sobre naturaleza. Apoyo de los estados del GBF (Kunming-Montreal 2022).",
    xrefRows: [
      { reportTitle: "TNFD Additional Sector Guidance 2026", date: "20 abr 2026",
        criterionCa: "TNFD publica guia per a 5 sectors addicionals: agricultura, alimentació, begudes, mineria, construcció.",
        criterionEs: "TNFD publica guía para 5 sectores adicionales: agricultura, alimentación, bebidas, minería, construcción.",
        impact: "high" },
      { reportTitle: "ESRS E4 (Biodiversity) Draft Update 2026", date: "8 mar 2026",
        criterionCa: "EFRAG actualitza ESRS E4 per alinear-se amb TNFD. 70% dels datapoints TNFD es mantenen.",
        criterionEs: "EFRAG actualiza ESRS E4 para alinearse con TNFD. 70% de los datapoints TNFD se mantienen.",
        impact: "high" },
      { reportTitle: "GBF (Kunming-Montreal) Implementation Update", date: "12 maig 2026",
        criterionCa: "Estat de compliment dels 23 targets del Global Biodiversity Framework. Empreses han de reportar target 15.",
        criterionEs: "Estado de cumplimiento de los 23 targets del Global Biodiversity Framework. Empresas deben reportar target 15.",
        impact: "med" },
      { reportTitle: "TNFD-TCFD Joint Guidance 2026", date: "30 mar 2026",
        criterionCa: "Guia conjunta per integrar reporting clima+natura. Una sola estratègia, dos reports complementaris.",
        criterionEs: "Guía conjunta para integrar reporting clima+naturaleza. Una sola estrategia, dos reports complementarios.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Realitzar avaluació LEAP (Locate, Evaluate, Assess, Prepare) per a pròpia cadena de valor",
        textEs: "Realizar evaluación LEAP (Locate, Evaluate, Assess, Prepare) para propia cadena de valor",
        sourceCa: "Font: TNFD LEAP Approach", sourceEs: "Fuente: TNFD LEAP Approach" },
      { num: "2", textCa: "Mapejar datapoints TNFD amb ESRS E4 per reporting integrat",
        textEs: "Mapear datapoints TNFD con ESRS E4 para reporting integrado",
        sourceCa: "Font: ESRS E4 Draft 2026", sourceEs: "Fuente: ESRS E4 Draft 2026" },
      { num: "3", textCa: "Identificar localitzacions d'alta importància per biodiversitat en operacions pròpies i proveïdors",
        textEs: "Identificar localizaciones de alta importancia para biodiversidad en operaciones propias y proveedores",
        sourceCa: "Font: TNFD Locate Phase", sourceEs: "Fuente: TNFD Locate Phase" },
      { num: "4", textCa: "Integrar reporting TNFD amb TCFD per a una estratègia unificada clima-natura",
        textEs: "Integrar reporting TNFD con TCFD para una estrategia unificada clima-naturaleza",
        sourceCa: "Font: TNFD-TCFD Joint Guidance", sourceEs: "Fuente: TNFD-TCFD Joint Guidance" },
    ],
  },

  // ============================================================
  // 14. TCFD
  // ============================================================
  "tcfd": {
    slug: "tcfd",
    name: "TCFD",
    type: "fw",
    access: "free",
    count: 4,
    logo: "/logos-estandards/tcfd.png",
    issuerCa: "Financial Stability Board (FSB) · 2017",
    issuerEs: "Financial Stability Board (FSB) · 2017",
    descCa: "Taskforce on Climate-related Financial Disclosures. Framework per reportar riscos i oportunitats financeres climàtiques. 4 pilars: Governance, Strategy, Risk Management, Metrics & Targets. Classificació de riscos: físics (aguts i crònics) i de transició (regulatoris, tecnològics, mercat, reputació). 4.800+ organitzacions suporten TCFD (2024). Base de l'ESRS E1 (canvi climàtic), ISSB S2, CDP i la majoria de regulacions climàtiques nacionals (UK, Japó, Singapur, Nova Zelanda). Dissolt el 2023 i integrat a l'ISSB, però la metodologia segueix sent la referència global.",
    descEs: "Taskforce on Climate-related Financial Disclosures. Framework para reportar riesgos y oportunidades financieras climáticas. 4 pilares: Governance, Strategy, Risk Management, Metrics & Targets. Clasificación de riesgos: físicos (agudos y crónicos) y de transición (regulatorios, tecnológicos, mercado, reputación). 4.800+ organizaciones soportan TCFD (2024). Base del ESRS E1 (cambio climático), ISSB S2, CDP y la mayoría de regulaciones climáticas nacionales (UK, Japón, Singapur, Nueva Zelanda). Disuelto en 2023 e integrado en ISSB, pero la metodología sigue siendo la referencia global.",
    xrefRows: [
      { reportTitle: "ISSB S2 (Climate) Implementation Update 2026", date: "28 mar 2026",
        criterionCa: "ISSB S2 integra completament TCFD. Empreses TCFD-compliant tenen 80% del camí S2 fet.",
        criterionEs: "ISSB S2 integra completamente TCFD. Empresas TCFD-compliant tienen 80% del camino S2 hecho.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "ESRS E1 manté estructura TCFD però afegeix doble materialitat. 4 pilars intactes.",
        criterionEs: "ESRS E1 mantiene estructura TCFD pero añade doble materialidad. 4 pilares intactes.",
        impact: "med" },
      { reportTitle: "SBTi Corporate Net-Zero Standard 2024", date: "10 feb 2026",
        criterionCa: "TCFD Metrics & Targets actualitzat per integrar SBTi targets. Compatible amb SBTi 1.5°C pathways.",
        criterionEs: "TCFD Metrics & Targets actualizado para integrar SBTi targets. Compatible con SBTi 1.5°C pathways.",
        impact: "high" },
      { reportTitle: "ECB Climate Risk Stress Test 2026", date: "5 abr 2026",
        criterionCa: "ECB realitza 3r stress test climàtic. Bancs han de reportar amb metodologia TCFD.",
        criterionEs: "ECB realiza 3º stress test climático. Bancos deben reportar con metodología TCFD.",
        impact: "high" },
    ],
    actions: [
      { num: "1", textCa: "Migrar reporting TCFD a ISSB S2 per comply amb nou estàndard global",
        textEs: "Migrar reporting TCFD a ISSB S2 para comply con nuevo estándar global",
        sourceCa: "Font: ISSB S2 Implementation", sourceEs: "Fuente: ISSB S2 Implementation" },
      { num: "2", textCa: "Realitzar anàlisi de transició climàtica (1,5°C, 2°C, 3°C scenarios) seguint TCFD",
        textEs: "Realizar análisis de transición climática (1,5°C, 2°C, 3°C escenarios) siguiendo TCFD",
        sourceCa: "Font: TCFD Technical Supplement", sourceEs: "Fuente: TCFD Technical Supplement" },
      { num: "3", textCa: "Avaluar riscos físics amb eines com CCRR o RCP scenarios per a operacions crítiques",
        textEs: "Evaluar riesgos físicos con herramientas como CCRR o RCP scenarios para operaciones críticas",
        sourceCa: "Font: TCFD Physical Risk Framework", sourceEs: "Fuente: TCFD Physical Risk Framework" },
      { num: "4", textCa: "Integrar targets SBTi en pilar Metrics & Targets del TCFD per a coherència",
        textEs: "Integrar targets SBTi en pilar Metrics & Targets del TCFD para coherencia",
        sourceCa: "Font: SBTi Corporate Net-Zero Standard", sourceEs: "Fuente: SBTi Corporate Net-Zero Standard" },
    ],
  },

  // ============================================================
  // 15. EMAS
  // ============================================================
  "emas": {
    slug: "emas",
    name: "EMAS",
    type: "reg",
    access: "free",
    count: 3,
    logo: "/logos-estandards/emas.png",
    issuerCa: "Comissió Europea · DG ENV",
    issuerEs: "Comisión Europea · DG ENV",
    descCa: "Eco-Management and Audit Scheme. Sistema comunitari d'eco-gestió i auditoria regulat pel Reglament (UE) 2017/1505. Voluntari però regulat (a diferència d'ISO 14001 que és estàndard privat). Més exigent: inclou declaració ambiental validada per verifier ambiental acreditat, compliment legal garantit, i millora contínua demostrable. 4.000+ organitzacions i 14.000+ centres a la UE (principalment Alemanya, Itàlia, Espanya). Espanya: 1.000+ centres, líder en hostaleria i administració local. Integrable amb ISO 14001 (basat en el mateix cicle PDCA). Renovació cada 3 anys.",
    descEs: "Eco-Management and Audit Scheme. Sistema comunitario de eco-gestión y auditoría regulado por el Reglamento (UE) 2017/1505. Voluntario pero regulado (a diferencia de ISO 14001 que es estándar privado). Más exigente: incluye declaración ambiental validada por verifier ambiental acreditado, cumplimiento legal garantizado, y mejora continua demostrable. 4.000+ organizaciones y 14.000+ centros en la UE (principalmente Alemania, Italia, España). España: 1.000+ centros, líder en hostelería y administración local. Integrable con ISO 14001 (basado en el mismo ciclo PDCA). Renovación cada 3 años.",
    xrefRows: [
      { reportTitle: "EMAS Regulation Review 2026: esborrany Comissió", date: "12 abr 2026",
        criterionCa: "Comissió prepara revisió EMAS per alinear amb ESRS E1-E5. Nous indicadors obligatoris.",
        criterionEs: "Comisión prepara revisión EMAS para alinear con ESRS E1-E5. Nuevos indicadores obligatorios.",
        impact: "high" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "Declaració ambiental EMAS pot servir com a evidència ESRS E2 (pollució) i E5 (circularitat).",
        criterionEs: "Declaración ambiental EMAS puede servir como evidencia ESRS E2 (polución) y E5 (circularidad).",
        impact: "med" },
      { reportTitle: "EU Taxonomy Delegated Act 2026", date: "28 mar 2026",
        criterionCa: "EMAS reconegut com a garantia de compliment DNSH (Do No Significant Harm) per a activitats Taxonomia.",
        criterionEs: "EMAS reconocido como garantía de cumplimiento DNSH (Do No Significant Harm) para actividades Taxonomía.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Integrar EMAS amb ISO 14001 si ja s'hi està certificat (estalvia 60% del treball d'auditoria)",
        textEs: "Integrar EMAS con ISO 14001 si ya se está certificado (ahorra 60% del trabajo de auditoría)",
        sourceCa: "Font: EMAS-ISO 14001 integration guide", sourceEs: "Fuente: EMAS-ISO 14001 integration guide" },
      { num: "2", textCa: "Preparar declaració ambiental amb dades ESRS E1-E5 per a doble ús",
        textEs: "Preparar declaración ambiental con datos ESRS E1-E5 para doble uso",
        sourceCa: "Font: EMAS Regulation Review 2026", sourceEs: "Fuente: EMAS Regulation Review 2026" },
      { num: "3", textCa: "Usar EMAS com a evidència DNSH en alineació Taxonomia UE",
        textEs: "Usar EMAS como evidencia DNSH en alineación Taxonomía UE",
        sourceCa: "Font: EU Taxonomy DA 2026", sourceEs: "Fuente: EU Taxonomy DA 2026" },
      { num: "4", textCa: "Renovar registre EMAS cada 3 anys amb verifier acreditat (no pot ser mateix que ISO 14001)",
        textEs: "Renovar registro EMAS cada 3 años con verifier acreditado (no puede ser mismo que ISO 14001)",
        sourceCa: "Font: Reglament (UE) 2017/1505", sourceEs: "Fuente: Reglamento (UE) 2017/1505" },
    ],
  },

  // ============================================================
  // 16. ISO 26000
  // ============================================================
  "iso-26000": {
    slug: "iso-26000",
    name: "ISO 26000",
    type: "fw",
    access: "free",
    count: 3,
    logo: "/logos-estandards/iso-26000.svg",
    issuerCa: "ISO · Ginebra (2010)",
    issuerEs: "ISO · Ginebra (2010)",
    descCa: "Guia internacional de responsabilitat social publicada per ISO el 2010. NO certificable (a diferència de la majoria d'estàndards ISO). Marc de referència amb 7 àrees nucli: governança organitzativa, drets humans, pràctiques laborals, medi ambient, pràctiques justes d'operació, assumptes de consumidors, participació i desenvolupament de la comunitat. 36 esferes d'acció. Adoptat per 80+ països com a estàndard nacional. Base d'estàndards certificables posteriors: ISO 26000-based SGE 21, ISO 20400 (sustainable procurement), ISO 37101 (desenvolupament sostenible comunitari). Revisió en cursor (2025-2026).",
    descEs: "Guía internacional de responsabilidad social publicada por ISO en 2010. NO certificable (a diferencia de la mayoría de estándares ISO). Marco de referencia con 7 áreas núcleo: gobernanza organizativa, derechos humanos, prácticas laborales, medio ambiente, prácticas justas de operación, asuntos de consumidores, participación y desarrollo de la comunidad. 36 esferas de acción. Adoptado por 80+ países como estándar nacional. Base de estándares certificables posteriores: ISO 26000-based SGE 21, ISO 20400 (sustainable procurement), ISO 37101 (desarrollo sostenible comunitario). Revisión en curso (2025-2026).",
    xrefRows: [
      { reportTitle: "ISO 26000 Revision 2026: Working Draft", date: "15 abr 2026",
        criterionCa: "ISO publica esborrany de revisió. Nous elements sobre canvi climàtic, drets digitals i IA.",
        criterionEs: "ISO publica borrador de revisión. Nuevos elementos sobre cambio climático, derechos digitales e IA.",
        impact: "high" },
      { reportTitle: "CSDDD Omnibus I: esmenes finals", date: "15 mar 2026",
        criterionCa: "ISO 26000 és marc de referència per a due diligence CSDDD. 7 àrees cobreixen tot el scope CSDDD.",
        criterionEs: "ISO 26000 es marco de referencia para due diligence CSDDD. 7 áreas cubren todo el scope CSDDD.",
        impact: "med" },
      { reportTitle: "Revisió dels ESRS: simplificació del CSRD", date: "6 may 2026",
        criterionCa: "ESRS social i de governança alineats amb ISO 26000. Mapping 1:1 disponible.",
        criterionEs: "ESRS social y de gobernanza alineados con ISO 26000. Mapping 1:1 disponible.",
        impact: "med" },
    ],
    actions: [
      { num: "1", textCa: "Usar ISO 26000 com a marc de referència intern per estructurar estratègia ESG",
        textEs: "Usar ISO 26000 como marco de referencia interno para estructurar estrategia ESG",
        sourceCa: "Font: ISO 26000:2010", sourceEs: "Fuente: ISO 26000:2010" },
      { num: "2", textCa: "Implementar ISO 20400 (sustainable procurement) per complementar ISO 26000",
        textEs: "Implementar ISO 20400 (sustainable procurement) para complementar ISO 26000",
        sourceCa: "Font: ISO 20400:2017", sourceEs: "Fuente: ISO 20400:2017" },
      { num: "3", textCa: "Preparar-se per a revisió ISO 26000:2026 amb noves àrees (clima, drets digitals, IA)",
        textEs: "Prepararse para revisión ISO 26000:2026 con nuevas áreas (clima, derechos digitales, IA)",
        sourceCa: "Font: ISO 26000 Revision Working Draft", sourceEs: "Fuente: ISO 26000 Revision Working Draft" },
      { num: "4", textCa: "Mapejar 7 àrees ISO 26000 amb ESRS social i de governança per reporting integrat",
        textEs: "Mapear 7 áreas ISO 26000 con ESRS social y de gobernanza para reporting integrado",
        sourceCa: "Font: ESRS-ISO 26000 mapping", sourceEs: "Fuente: ESRS-ISO 26000 mapping" },
    ],
  },
};
